language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25

before_install
  - openssl aes-256-cbc -K $encrypted_bdeebbcbca30_key -iv $encrypted_bdeebbcbca30_iv -in google-services.json.enc -out twilio-auth-sample/google-services.json -d
